### ISSUE TITLE
"Test Pattern" probe initialization is incorrect

### ISSUE THREAD

**Issue by carterbox** [AdvancedPhotonSource/ptychodus#43]
The amplitude and phase of this test pattern should follow polar coordinates. 

The amplitude of this test pattern is correct. Is a function of the radius: 0 in the center at 1 at the edge of the unit circle.

The phase is incorrect. It should be the angle. But for some reason with the twilight color map, the phase is constant for most of the circle, then goes from -pi to pi in one small section.

![test_pattern](https://user-images.githubusercontent.com/9604511/189182144-bfa30d61-f2b2-4c1e-833a-b13d95224e7c.png)

**Comment by stevehenke** [comment]
The attached image can be reproduced by setting the data range of the colormap to 0..1 (the default). If you hit the "auto" button, it adjusts to -pi..pi and everything looks okay.
